[theme]
primaryColor = "#3498db"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#2c3e50"
font = "sans serif"

[server]
maxUploadSize = 100
enableXsrfProtection = true
enableCORS = true
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
